2022-01-10 14:30:39,110 - phil - -log- log.py -ERROR 29 - 断言状态码错误，状态码应为：200实际为：401，返回值为{'code': 20000, 'error': '无操作权限'}
2022-01-10 14:49:54,586 - phil-log-log.py-ERROR-29-断言状态码错误，状态码应为：200实际为：401，返回值为{'code': 20000, 'error': '无操作权限'}
2022-01-10 14:50:01,060 - phil-log-log.py-ERROR-29-断言状态码错误，状态码应为：200实际为：401，返回值为{'code': 20000, 'error': '无操作权限'}
2022-01-10 14:51:26,308 - phil-log-log.py-ERROR-29-断言状态码错误，状态码应为：200,实际为：401，返回值为{'code': 20000, 'error': '无操作权限'}
2022-01-10 14:51:43,545 - phil-log-log.py-ERROR-29-断言状态码错误，状态码应为：200,实际为：401，返回值为{'code': 20000, 'error': '无操作权限'}
2022-01-10 15:13:59,505 - phil-log-log.py-ERROR-29-断言状态码错误，状态码应为：200,实际为：401，返回值为{'code': 20000, 'error': '无操作权限'}
2022-01-10 15:56:27,922 - phil-log-log.py-ERROR-29-断言状态码错误，状态码应为：200,实际为：401，返回值为{'code': 20000, 'error': '无操作权限'}
2022-01-10 15:58:37,289 - phil-log-log.py-ERROR-29-断言状态码错误，状态码应为：200,实际为：401，返回值为{'code': 20000, 'error': '无操作权限'}
2022-01-10 15:58:47,514 - phil-log-log.py-ERROR-29-断言状态码错误，状态码应为：200,实际为：401，返回值为{'code': 20000, 'error': '无操作权限'}
2022-01-10 16:03:08,965 - phil-log-log.py-ERROR-29-断言状态码错误，状态码应为：200,实际为：401，返回值为{'code': 20000, 'error': '无操作权限'}
2022-01-10 16:12:43,696 - phil-log-log.py-ERROR-29-'id'帐号或密码错误 错误信息为：{'code': 2, 'error': '用户名或者密码错误'}
2022-01-10 16:12:56,843 - phil-log-log.py-ERROR-29-'id'帐号或密码错误 错误信息为：{'code': 2, 'error': '用户名或者密码错误'}
2022-01-25 15:09:46,180 - phil-log-log.py-ERROR-29-https://ticketapitest.shomes.cn/-/point-sand-factory/add接口报错，预期返回值：{'message': '请求成功'},实际返回值：{'message': '请求成功'},预期状态码：200，实际状态码：200
2022-01-25 15:22:58,578 - phil-log-log.py-ERROR-29-'id'帐号或密码错误 错误信息为：{'code': 14, 'error': 'Socket closed'}
2022-01-25 15:27:16,209 - phil-log-log.py-ERROR-29-'id'帐号或密码错误 错误信息为：{'code': 14, 'error': 'Socket closed'}
2022-01-25 15:28:30,619 - phil-log-log.py-ERROR-29-'id'帐号或密码错误 错误信息为：{'code': 14, 'error': 'Socket closed'}
2022-01-26 10:29:07,416 - phil-log-log.py-ERROR-29-https://ticketapitest.shomes.cn/-/point-sand-factory/add 接口报错，预期返回值：{'message': '请求成功'},实际返回值：{'message': '请求成功'},预期状态码：200，实际状态码：200
2022-01-26 10:29:20,655 - phil-log-log.py-ERROR-29-(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'message': '请求成功'}','2022-01-26 10:29:00')' at line 1")
2022-01-26 11:30:18,481 - phil-log-log.py-ERROR-29-https://ticketapitest.shomes.cn/-/point-sand-factory/add 接口报错，预期返回值：{'message': '请求成功'},实际返回值：{'message': '请求成功'},预期状态码：200，实际状态码：200
2022-01-26 11:30:18,519 - phil-log-log.py-ERROR-29-(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'message': '请求成功'}','2022-01-26 11:30:18')' at line 1")
2022-01-26 11:31:57,011 - phil-log-log.py-ERROR-29-https://ticketapitest.shomes.cn/-/point-sand-factory/add 接口报错，预期返回值：{'message': '请求成功'},实际返回值：{'message': '请求成功'},预期状态码：200，实际状态码：200
2022-01-26 11:52:53,295 - phil-log-log.py-ERROR-29-(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'message': '请求成功'}','2022-01-26 11:50:54')' at line 1")
2022-01-26 14:24:37,888 - phil-log-log.py-ERROR-29-'id'帐号或密码错误 错误信息为：{'code': 14, 'error': 'Socket closed'}
2022-01-26 14:26:59,797 - phil-log-log.py-ERROR-29-(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'message': '请求成功'}','2022-01-26 14:26:09')' at line 1")
2022-01-26 14:31:14,990 - phil-log-log.py-ERROR-29-(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''message': '请求成功'},'2022-01-26 14:29:40')' at line 1")
2022-01-27 14:37:46,594 - phil-log-log.py-ERROR-29-'id'帐号或密码错误 错误信息为：{'code': 14, 'error': 'Socket closed'}
2022-01-27 14:41:20,439 - phil-log-log.py-ERROR-29-'id'帐号或密码错误 错误信息为：{'code': 14, 'error': 'failed to connect to all addresses'}
2022-01-27 19:24:23,807 - phil-log-log.py-ERROR-29-(1054, "Unknown column 'deleted' in 'where clause'")
2022-01-27 19:36:57,811 - __name__-log-log.py-ERROR-29-'id'帐号或密码错误 错误信息为：{'code': 14, 'error': 'Socket closed'}
2022-01-27 19:38:15,678 - tools.log-log-log.py-ERROR-29-https://ticketapitest.shomes.cn/-/point-sand-factory/list 接口报错，预期返回值：{"data":[{"id":145,"name":"游飞3测试砂石场","sand_factory_type":null,"address":"123","lng":"93.4115991","lat":"31.3813051","area":"0.00","image":null,"open_status":1,"deleted":0,"area_id":8,"department_id":584,"plan":"file\/10\/2022\/0107\/b843f996-9eaf-47a6-ada1-0d5c49924756.png","create_time":"2022-01-20
09:52:42","pm_2_5":null,"pm_10":0,"temperature":null,"humidity":null,"aqi":null,"b_pm_2_5":null,"b_pm_10":null,"b_temperature":null,"b_humidity":null,"b_aqi":null,"realname":null,"street_id":null,"manager_department_id":null,"constructor_manager":null,"constructor_manager_telephone":null,"consum_type":2,"forever":1,"begin_time":null,"end_time":null,"other_info":"","videos":"","images":"","created_by":26679,"area_name":"高新区","report_method":1,"gps_polygon":2,"user_name":"游飞"}],"page":{"page":1,"limit":10,"total":1}},实际返回值：{'data': [{'id': 177, 'name': '游飞3测试砂石场', 'sand_factory_type': None, 'address': '123', 'lng': '93.4115991', 'lat': '31.3813051', 'area': '0.00', 'image': None, 'open_status': 1, 'deleted': 0, 'area_id': 8, 'department_id': 584, 'plan': 'file/10/2022/0107/b843f996-9eaf-47a6-ada1-0d5c49924756.png', 'create_time': '2022-01-27 19:38:10', 'pm_2_5': None, 'pm_10': 0, 'temperature': None, 'humidity': None, 'aqi': None, 'b_pm_2_5': None, 'b_pm_10': None, 'b_temperature': None, 'b_humidity': None, 'b_aqi': None, 'realname': None, 'street_id': None, 'manager_department_id': None, 'constructor_manager': None, 'constructor_manager_telephone': None, 'consum_type': 2, 'forever': 1, 'begin_time': None, 'end_time': None, 'other_info': '', 'videos': '', 'images': '', 'created_by': 89089, 'area_name': '高新区', 'report_method': 1, 'gps_polygon': 1, 'user_name': '测试--游飞--总部坐席'}], 'page': {'page': 1, 'limit': 10, 'total': 1}},预期状态码：200，实际状态码：200
2022-01-27 20:09:37,147 - phil-log-log.py-ERROR-29-(1054, "Unknown column 'deleted' in 'where clause'")
2022-01-28 12:00:33,426 - phil-log-log.py-ERROR-41-(1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'"id": 172} where id=3\' at line 1')
2022-01-28 12:00:48,159 - phil-log-log.py-ERROR-41-(1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'"id": 172} where id=3\' at line 1')
2022-01-28 12:01:25,364 - phil-log-log.py-ERROR-41-(1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'"id": 172} where id=3\' at line 1')
2022-01-28 12:01:40,633 - phil-log-log.py-ERROR-41-(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''id': 172} where id=3' at line 1")
2022-01-28 12:02:20,901 - phil-log-log.py-ERROR-41-(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''id': 172} where id=3' at line 1")
2022-01-28 12:02:42,981 - phil-log-log.py-ERROR-41-(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''id': 172} where id=3' at line 1")
2022-01-28 14:06:29,479 - phil-log-log.py-ERROR-41-(1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'id": 174}"where id=3\' at line 1')
2022-01-28 14:06:42,800 - phil-log-log.py-ERROR-41-(1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'"id": 174} where id=3\' at line 1')
2022-01-28 14:06:43,942 - phil-log-log.py-ERROR-41-(1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'"id": 174} where id=3\' at line 1')
2022-01-28 14:11:58,937 - phil-log-log.py-ERROR-41-'id'帐号或密码错误 错误信息为：{'code': 14, 'error': 'Socket closed'}
2022-01-28 14:12:37,716 - phil-log-log.py-ERROR-41-'id'帐号或密码错误 错误信息为：{'code': 14, 'error': 'Socket closed'}
2022-01-28 14:15:29,444 - phil-log-log.py-ERROR-41-'id'帐号或密码错误 错误信息为：{'code': 14, 'error': 'Socket closed'}
2022-01-28 14:17:15,306 - phil-log-log.py-ERROR-41-'id'帐号或密码错误 错误信息为：{'code': 14, 'error': 'Socket closed'}
2022-01-28 14:17:18,415 - phil-log-log.py-ERROR-41-'id'帐号或密码错误 错误信息为：{'code': 14, 'error': 'failed to connect to all addresses'}
2022-01-28 15:22:02,010 - phil-log-log.py-ERROR-41-帐号或密码错误 错误信息为：{'code': 14, 'error': 'failed to connect to all addresses'}
2022-01-28 15:22:46,727 - phil-log-log.py-ERROR-41-帐号或密码错误 错误信息为：{'code': 14, 'error': 'failed to connect to all addresses'}
2022-01-28 15:39:50,613 - phil-log-log.py-ERROR-41-(1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'id": 177}"where id=3\' at line 1')
2022-01-28 15:49:58,873 - phil-log-log.py-ERROR-41-(1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'id": 177}" where id=3\' at line 1')
2022-01-28 15:55:05,996 - phil-log-log.py-ERROR-41-(1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'id": 181}" where id=3\' at line 1')
2022-01-28 15:57:42,380 - phil-log-log.py-ERROR-41-(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'id': 181}' where id=3' at line 1")
2022-01-28 17:47:18,280 - phil-log-log.py-ERROR-41-帐号或密码错误 错误信息为：{'code': 14, 'error': 'Socket closed'}
2022-01-28 17:48:13,286 - phil-log-log.py-ERROR-41-帐号或密码错误 错误信息为：{'code': 14, 'error': 'Socket closed'}
2022-01-28 17:50:03,756 - phil-log-log.py-ERROR-41-帐号或密码错误 错误信息为：{'code': 14, 'error': 'Socket closed'}
2022-01-28 17:50:10,571 - phil-log-log.py-ERROR-41-帐号或密码错误 错误信息为：{'code': 14, 'error': 'Socket closed'}
2022-01-28 17:55:16,814 - phil-log-log.py-ERROR-41-帐号或密码错误 错误信息为：{'code': 14, 'error': 'failed to connect to all addresses'}
2022-01-28 17:55:21,878 - phil-log-log.py-ERROR-41-帐号或密码错误 错误信息为：{'code': 14, 'error': 'failed to connect to all addresses'}
2022-01-28 17:57:16,343 - phil-log-log.py-ERROR-41-帐号或密码错误 错误信息为：{'code': 14, 'error': 'failed to connect to all addresses'}
2022-01-28 17:58:22,275 - phil-log-log.py-ERROR-41-帐号或密码错误 错误信息为：{'code': 14, 'error': 'failed to connect to all addresses'}
2022-01-28 18:05:10,236 - phil-log-log.py-ERROR-41-帐号或密码错误 错误信息为：{'code': 14, 'error': 'failed to connect to all addresses'}
2022-01-28 18:07:03,609 - phil-log-log.py-ERROR-41-帐号或密码错误 错误信息为：{'code': 14, 'error': 'failed to connect to all addresses'}
2022-01-28 18:07:27,589 - phil-log-log.py-ERROR-41-帐号或密码错误 错误信息为：{'code': 14, 'error': 'failed to connect to all addresses'}
2022-01-28 18:07:58,040 - phil-log-log.py-ERROR-41-帐号或密码错误 错误信息为：{'code': 14, 'error': 'failed to connect to all addresses'}
2022-01-28 18:14:41,903 - phil-log-log.py-ERROR-41-https://ticketapitest.shomes.cn/-/point-sand-factory/add 接口报错，预期返回值：{'message': '请求成功'},实际返回值：{'code': 10010, 'error': '登录凭证错误'},预期状态码：200，实际状态码：401
2022-01-28 18:14:42,048 - phil-log-log.py-ERROR-41-https://ticketapitest.shomes.cn/-/point-sand-factory/add 接口报错，预期返回值：{'message': '请求成功'},实际返回值：{'code': 10010, 'error': '登录凭证错误'},预期状态码：200，实际状态码：401
2022-01-28 18:21:31,557 - phil-log-log.py-ERROR-41-https://ticketapitest.shomes.cn/-/point-sand-factory/add 接口报错，预期返回值：{'message': '请求成功'},实际返回值：{'code': 10010, 'error': '登录凭证错误'},预期状态码：200，实际状态码：401
2022-01-28 18:21:31,669 - phil-log-log.py-ERROR-41-https://ticketapitest.shomes.cn/-/point-sand-factory/add 接口报错，预期返回值：{'message': '请求成功'},实际返回值：{'code': 10010, 'error': '登录凭证错误'},预期状态码：200，实际状态码：401
2022-01-28 18:22:26,119 - phil-log-log.py-ERROR-41-https://ticketapitest.shomes.cn/-/point-sand-factory/add 接口报错，预期返回值：{'message': '请求成功'},实际返回值：{'code': 10010, 'error': '登录凭证错误'},预期状态码：200，实际状态码：401
2022-01-28 18:22:26,233 - phil-log-log.py-ERROR-41-https://ticketapitest.shomes.cn/-/point-sand-factory/add 接口报错，预期返回值：{'message': '请求成功'},实际返回值：{'code': 10010, 'error': '登录凭证错误'},预期状态码：200，实际状态码：401
2022-01-28 18:22:43,530 - phil-log-log.py-ERROR-41-帐号或密码错误 错误信息为：{'code': 14, 'error': 'failed to connect to all addresses'}
2022-01-28 18:22:49,069 - phil-log-log.py-ERROR-41-https://ticketapitest.shomes.cn/-/point-sand-factory/add 接口报错，预期返回值：{'message': '请求成功'},实际返回值：{'code': 10010, 'error': '登录凭证错误'},预期状态码：200，实际状态码：401
2022-01-28 18:22:49,195 - phil-log-log.py-ERROR-41-https://ticketapitest.shomes.cn/-/point-sand-factory/add 接口报错，预期返回值：{'message': '请求成功'},实际返回值：{'code': 10010, 'error': '登录凭证错误'},预期状态码：200，实际状态码：401
2022-01-28 18:22:56,065 - phil-log-log.py-ERROR-41-https://ticketapitest.shomes.cn/-/point-sand-factory/add 接口报错，预期返回值：{'message': '请求成功'},实际返回值：{'code': 10010, 'error': '登录凭证错误'},预期状态码：200，实际状态码：401
2022-01-28 18:22:56,185 - phil-log-log.py-ERROR-41-https://ticketapitest.shomes.cn/-/point-sand-factory/add 接口报错，预期返回值：{'message': '请求成功'},实际返回值：{'code': 10010, 'error': '登录凭证错误'},预期状态码：200，实际状态码：401
2022-01-28 18:22:59,571 - phil-log-log.py-ERROR-41-https://ticketapitest.shomes.cn/-/point-sand-factory/add 接口报错，预期返回值：{'message': '请求成功'},实际返回值：{'code': 10010, 'error': '登录凭证错误'},预期状态码：200，实际状态码：401
2022-01-28 18:22:59,707 - phil-log-log.py-ERROR-41-https://ticketapitest.shomes.cn/-/point-sand-factory/add 接口报错，预期返回值：{'message': '请求成功'},实际返回值：{'code': 10010, 'error': '登录凭证错误'},预期状态码：200，实际状态码：401
2022-01-28 18:24:50,629 - phil-log-log.py-ERROR-41-帐号或密码错误 错误信息为：{'code': 14, 'error': 'failed to connect to all addresses'}
2022-01-28 18:24:56,566 - phil-log-log.py-ERROR-41-https://ticketapitest.shomes.cn/-/point-sand-factory/list 接口报错，预期返回值：{"data":[{"id":145,"name":"游飞3测试砂石场","sand_factory_type":null,"address":"123","lng":"93.4115991","lat":"31.3813051","area":"0.00","image":null,"open_status":1,"deleted":0,"area_id":8,"department_id":584,"plan":"file\/10\/2022\/0107\/b843f996-9eaf-47a6-ada1-0d5c49924756.png","create_time":"2022-01-20
09:52:42","pm_2_5":null,"pm_10":0,"temperature":null,"humidity":null,"aqi":null,"b_pm_2_5":null,"b_pm_10":null,"b_temperature":null,"b_humidity":null,"b_aqi":null,"realname":null,"street_id":null,"manager_department_id":null,"constructor_manager":null,"constructor_manager_telephone":null,"consum_type":2,"forever":1,"begin_time":null,"end_time":null,"other_info":"","videos":"","images":"","created_by":26679,"area_name":"高新区","report_method":1,"gps_polygon":2,"user_name":"游飞"}],"page":{"page":1,"limit":10,"total":1}},实际返回值：{'data': [{'id': 182, 'name': '游飞3测试砂石场', 'sand_factory_type': None, 'address': '123', 'lng': '93.4115991', 'lat': '31.3813051', 'area': '0.00', 'image': None, 'open_status': 1, 'deleted': 0, 'area_id': 8, 'department_id': 584, 'plan': 'file/10/2022/0107/b843f996-9eaf-47a6-ada1-0d5c49924756.png', 'create_time': '2022-01-28 18:24:52', 'pm_2_5': None, 'pm_10': 0, 'temperature': None, 'humidity': None, 'aqi': None, 'b_pm_2_5': None, 'b_pm_10': None, 'b_temperature': None, 'b_humidity': None, 'b_aqi': None, 'realname': None, 'street_id': None, 'manager_department_id': None, 'constructor_manager': None, 'constructor_manager_telephone': None, 'consum_type': 2, 'forever': 1, 'begin_time': None, 'end_time': None, 'other_info': '', 'videos': '', 'images': '', 'created_by': 89089, 'area_name': '高新区', 'report_method': 1, 'gps_polygon': 1, 'user_name': '测试--游飞--总部坐席'}], 'page': {'page': 1, 'limit': 10, 'total': 1}},预期状态码：200，实际状态码：200
2022-01-28 18:25:02,451 - phil-log-log.py-ERROR-41-帐号或密码错误 错误信息为：{'code': 14, 'error': 'failed to connect to all addresses'}
2022-01-28 18:25:08,968 - phil-log-log.py-ERROR-41-https://ticketapitest.shomes.cn/-/point-sand-factory/list 接口报错，预期返回值：{"data":[{"id":145,"name":"游飞3测试砂石场","sand_factory_type":null,"address":"123","lng":"93.4115991","lat":"31.3813051","area":"0.00","image":null,"open_status":1,"deleted":0,"area_id":8,"department_id":584,"plan":"file\/10\/2022\/0107\/b843f996-9eaf-47a6-ada1-0d5c49924756.png","create_time":"2022-01-20
09:52:42","pm_2_5":null,"pm_10":0,"temperature":null,"humidity":null,"aqi":null,"b_pm_2_5":null,"b_pm_10":null,"b_temperature":null,"b_humidity":null,"b_aqi":null,"realname":null,"street_id":null,"manager_department_id":null,"constructor_manager":null,"constructor_manager_telephone":null,"consum_type":2,"forever":1,"begin_time":null,"end_time":null,"other_info":"","videos":"","images":"","created_by":26679,"area_name":"高新区","report_method":1,"gps_polygon":2,"user_name":"游飞"}],"page":{"page":1,"limit":10,"total":1}},实际返回值：{'data': [{'id': 183, 'name': '游飞3测试砂石场', 'sand_factory_type': None, 'address': '123', 'lng': '93.4115991', 'lat': '31.3813051', 'area': '0.00', 'image': None, 'open_status': 1, 'deleted': 0, 'area_id': 8, 'department_id': 584, 'plan': 'file/10/2022/0107/b843f996-9eaf-47a6-ada1-0d5c49924756.png', 'create_time': '2022-01-28 18:25:04', 'pm_2_5': None, 'pm_10': 0, 'temperature': None, 'humidity': None, 'aqi': None, 'b_pm_2_5': None, 'b_pm_10': None, 'b_temperature': None, 'b_humidity': None, 'b_aqi': None, 'realname': None, 'street_id': None, 'manager_department_id': None, 'constructor_manager': None, 'constructor_manager_telephone': None, 'consum_type': 2, 'forever': 1, 'begin_time': None, 'end_time': None, 'other_info': '', 'videos': '', 'images': '', 'created_by': 89089, 'area_name': '高新区', 'report_method': 1, 'gps_polygon': 1, 'user_name': '测试--游飞--总部坐席'}], 'page': {'page': 1, 'limit': 10, 'total': 1}},预期状态码：200，实际状态码：200
2022-01-28 18:25:53,085 - phil-log-log.py-ERROR-41-帐号或密码错误 错误信息为：{'code': 14, 'error': 'failed to connect to all addresses'}
2022-01-28 18:26:19,042 - phil-log-log.py-ERROR-41-帐号或密码错误 错误信息为：{'code': 14, 'error': 'failed to connect to all addresses'}
2022-01-28 18:26:26,061 - phil-log-log.py-ERROR-41-帐号或密码错误 错误信息为：{'code': 14, 'error': 'failed to connect to all addresses'}
2022-01-28 18:28:02,588 - phil-log-log.py-ERROR-41-帐号或密码错误 错误信息为：{'code': 14, 'error': 'failed to connect to all addresses'}
2022-01-28 18:28:08,598 - phil-log-log.py-ERROR-41-帐号或密码错误 错误信息为：{'code': 14, 'error': 'failed to connect to all addresses'}
2022-01-28 18:29:30,405 - phil-log-log.py-ERROR-41-帐号或密码错误 错误信息为：{'code': 14, 'error': 'failed to connect to all addresses'}
2022-01-28 18:42:21,544 - phil-log-log.py-ERROR-41-https://ticketapitest.shomes.cn/-/point-sand-factory/delete 接口报错，预期返回值：{"message":"请求成功"},实际返回值：{'message': '请求成功'},预期状态码：200，实际状态码：200
2022-01-28 18:42:21,655 - phil-log-log.py-ERROR-41-https://ticketapitest.shomes.cn/-/point-sand-factory/delete 接口报错，预期返回值：{"message":"请求成功"},实际返回值：{'message': '请求成功'},预期状态码：200，实际状态码：200
2022-01-28 18:44:13,688 - phil-log-log.py-ERROR-41-https://ticketapitest.shomes.cn/-/point-sand-factory/list 接口报错，预期返回值：{"data":[],"page":{"page":1,"limit":10,"total":0}},实际返回值：{'data': [], 'page': {'page': 1, 'limit': 10, 'total': 0}},预期状态码：200，实际状态码：200
2022-01-28 18:44:13,819 - phil-log-log.py-ERROR-41-https://ticketapitest.shomes.cn/-/point-sand-factory/list 接口报错，预期返回值：{"data":[],"page":{"page":1,"limit":10,"total":0}},实际返回值：{'data': [], 'page': {'page': 1, 'limit': 10, 'total': 0}},预期状态码：200，实际状态码：200
2022-01-28 18:45:24,158 - phil-log-log.py-ERROR-41-https://ticketapitest.shomes.cn/-/point-sand-factory/list 接口报错，预期返回值：{"data":[],"page":{"page":1,"limit":10,"total":0}},实际返回值：{'data': [], 'page': {'page': 1, 'limit': 10, 'total': 0}},预期状态码：200，实际状态码：200
2022-01-28 18:45:24,291 - phil-log-log.py-ERROR-41-https://ticketapitest.shomes.cn/-/point-sand-factory/list 接口报错，预期返回值：{"data":[],"page":{"page":1,"limit":10,"total":0}},实际返回值：{'data': [], 'page': {'page': 1, 'limit': 10, 'total': 0}},预期状态码：200，实际状态码：200
2022-01-28 18:48:56,953 - phil-log-log.py-ERROR-41-https://ticketapitest.shomes.cn/-/point-sand-factory/list 接口报错，预期返回值：{"data":[],"page":{"page":1,"limit":10,"total":0}},实际返回值：{'data': [], 'page': {'page': 1, 'limit': 10, 'total': 0}},预期状态码：200，实际状态码：200
2022-01-28 18:48:57,085 - phil-log-log.py-ERROR-41-https://ticketapitest.shomes.cn/-/point-sand-factory/list 接口报错，预期返回值：{"data":[],"page":{"page":1,"limit":10,"total":0}},实际返回值：{'data': [], 'page': {'page': 1, 'limit': 10, 'total': 0}},预期状态码：200，实际状态码：200
2022-01-28 18:50:21,644 - phil-log-log.py-ERROR-41-https://ticketapitest.shomes.cn/-/point-sand-factory/list 接口报错，预期返回值：{"data":[],"page":{"page":1,"limit":10,"total":0}},实际返回值：{'data': [], 'page': {'page': 1, 'limit': 10, 'total': 0}},预期状态码：200，实际状态码：200
2022-01-28 18:50:21,745 - phil-log-log.py-ERROR-41-https://ticketapitest.shomes.cn/-/point-sand-factory/list 接口报错，预期返回值：{"data":[],"page":{"page":1,"limit":10,"total":0}},实际返回值：{'data': [], 'page': {'page': 1, 'limit': 10, 'total': 0}},预期状态码：200，实际状态码：200
